//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcOgrenciKayit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public int StudentId { get; set; }
        public string StudentAd { get; set; }
        public string StudentSoyad { get; set; }
        public string StudentMail { get; set; }
        public string StudentiFotograf { get; set; }
        public string StudentAdres { get; set; }
    }
}
